version: "3.9"

services:
  auth-service:
    image: ghcr.io/${OWNER_LC}/paychase-auth:latest
    container_name: paychase-auth
    restart: unless-stopped
    env_file: .env
    ports:
      - "5261:5261"
    networks:
      - paychase_net

networks:
  paychase_net:
    external: true
